version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "${APP_PORT:-8035}:80"
    volumes:
      - .:/src
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
      - db
  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      target: build
    volumes:
        - .:/src
    depends_on:
      - db
  db:
    container_name: db
    platform: linux/x86_64
    image: mysql:8.0
    ports:
      - "33070:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/init-testing-db.sql:/docker-entrypoint-initdb.d/init-testing-db.sql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: supersecret
