<?php

namespace Tests\Feature\V1\Http\Controllers\Api;
use App\Models\Chapter;
use App\Models\User;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Lang;
use Symfony\Component\HttpFoundation\Response;
use Tests\TestCase;
use function route;

class


ChapterVoteTest extends TestCase
{
    use WithFaker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed();
        $this->user = User::factory()->create();

        $this->chapter = Chapter::factory()->create();
    }

    public function testStoreOk()
    {
        $response = $this->actingAs($this->user)
            ->postJson(route('vote.rate', [getMorphedType($this->chapter::class), $this->chapter->id]));

        $response->assertOk()
            ->assertJsonFragment([
                'message' => Lang::get('rateable.create')
            ]);
    }

    public function testStoreUnauthorized()
    {
        $response = $this
            ->postJson(route('vote.rate', [getMorphedType($this->chapter::class), $this->chapter->id]));

        $response->assertUnauthorized();
    }

    public function testUpdateOk()
    {
        $this->actingAs($this->user)
            ->postJson(route('vote.rate', [getMorphedType($this->chapter::class), $this->chapter->id]));

        $response = $this->actingAs($this->user)
            ->postJson(route('vote.rate', [getMorphedType($this->chapter::class), $this->chapter->id]));

        $response->assertOk()
            ->assertJsonFragment([
                'message' => Lang::get('rateable.create')
            ]);
    }

    public function testDeleteOk()
    {
        $this->actingAs($this->user)
            ->postJson(route('vote.rate', [getMorphedType($this->chapter::class), $this->chapter->id]));

        $response = $this->actingAs($this->user)
            ->deleteJson(route('vote.un-rate', [getMorphedType($this->chapter::class), $this->chapter->id]));

        $response->assertOk()
            ->assertJsonFragment([
                'message' => Lang::get('rateable.delete')
            ]);
    }

    public function testDeleteBusy()
    {
        $response = $this->actingAs($this->user)
            ->deleteJson(route('vote.un-rate', [getMorphedType($this->chapter::class), $this->chapter->id]));

        $response->assertStatus(Response::HTTP_BAD_REQUEST)
            ->assertJsonFragment([
                'message' => Lang::get('rateable.notFound')
            ]);
    }

    public function testDeleteUnauthorized()
    {
        $response = $this
            ->deleteJson(route('vote.un-rate', [getMorphedType($this->chapter::class), $this->chapter->id]));

        $response->assertUnauthorized();
    }
}
